version: '3.7'

services:
  docker.mysql:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456@sql
    volumes:
      - /usr/mysql:/var/lib/mysql
    networks:
      - momo-net

  momo:
    build: /usr/wwwroot/momo/
    restart: always
    depends_on:
      - docker.mysql
    networks:
      - momo-net

  docker.nginx:
    image: nginx
    ports:
      - "8080:8080"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - momo
    networks:
      - momo-net

networks:
  momo-net:
    driver: bridge